# Generated by Django 5.2.4 on 2025-08-15 15:27

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="content",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name="project",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
