# Generated by Django 5.2.4 on 2025-08-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_blogpost_likes_blogpost_views_project_likes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("linkedin", "LinkedIn"),
                            ("github", "GitHub"),
                            ("instagram", "Instagram"),
                            ("youtube", "YouTube"),
                        ],
                        max_length=50,
                    ),
                ),
                ("url", models.URLField()),
            ],
        ),
    ]
