# Generated by Django 5.2.4 on 2025-08-20 15:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_sociallink"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="about/")),
            ],
        ),
        migrations.CreateModel(
            name="Hero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "greeting",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        default="Hi 👋, I'm", max_length=255
                    ),
                ),
                (
                    "name",
                    ckeditor_uploader.fields.RichTextUploadingField(max_length=100),
                ),
                (
                    "subtitle",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, max_length=255
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="hero/")),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    ckeditor_uploader.fields.RichTextUploadingField(max_length=100),
                ),
                (
                    "role",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, max_length=100
                    ),
                ),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
                ("featured", models.BooleanField(default=False)),
            ],
        ),
    ]
