# Generated by Django 5.2.4 on 2025-08-20 15:37

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_about_hero_testimonial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hero",
            name="greeting",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                default="Hi 👋, welcome to", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="hero",
            name="subtitle",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="name",
            field=ckeditor_uploader.fields.RichTextUploadingField(max_length=300),
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="role",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, max_length=300
            ),
        ),
    ]
