# Generated by Django 5.2.4 on 2025-08-20 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_hero_greeting_alter_hero_subtitle_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="about",
            name="image",
        ),
    ]
