# Generated by Django 5.2.4 on 2025-08-20 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_about_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hero",
            name="greeting",
            field=models.CharField(default="Hi 👋, welcome to", max_length=255),
        ),
        migrations.AlterField(
            model_name="hero",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
