# Generated by Django 5.2.4 on 2025-08-20 16:52

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_hero_greeting_alter_hero_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subtitle", models.CharField(blank=True, max_length=255, null=True)),
                ("description", ckeditor_uploader.fields.RichTextUploadingField()),
                (
                    "icon",
                    models.CharField(
                        help_text="Add emoji or icon code e.g., ⭐️, 💼, 🎖️",
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
