# Generated by Django 5.2.4 on 2025-08-20 17:55

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="OurStory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Our Story", max_length=255)),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
            ],
        ),
        migrations.CreateModel(
            name="WhyChooseUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="Why Choose Us", max_length=255)),
                (
                    "points",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        help_text="Use bullet points or HTML list here"
                    ),
                ),
            ],
        ),
    ]
