# Generated by Django 5.2.4 on 2025-08-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_ourstory_whychooseus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="excerpt",
            field=models.TextField(blank=True),
        ),
    ]
