# Generated by Django 5.2.4 on 2025-08-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_blogpost_excerpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
